name: "node_14_app"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    user: "root" # NOT SAFE FOR PRODUCTION!!
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/home/node/app
    ports: 
      - 3000:3000
      - 9009:9009
    command: "tail -F anything"

    # Log in to the container to install, start node, etc.
