name: "node_14_storybook"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    user: "node" # use root if you get stuck. root is NOT SAFE FOR PRODUCTION!!
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/intranet:/home/node/app # update external path as needed
    ports: 
      - 9009:9009
    command: "tail -F anything"
